apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
      namespace: factory
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          imagePullPolicy: Always
          image: juliantheking/users-service
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-credentials
                  key: POSTRGES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD