apiVersion: v1
kind: Service
metadata:
  name: users-service-svc
spec:
  selector:
    app: users-service-deployment
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080